#!/usr/bin/env bash
# Bash script Requirements:
#       Configure HAproxy so that it send traffic to web-01 and web-02
#       Distribute requests using a roundrobin algorithm
#       Make sure that HAproxy can be managed via an init script

sudo apt-get update
sudo apt-get install -y haproxy
# sudo chown -R $USER /etc/haproxy/haproxy.cfg
sudo echo "
frontend client
        mode http
        bind :80
        default_backend my_servers

backend my_servers
        mode http
        server web-01 35.175.132.124:80
        server web-02 54.237.219.9
        balance roundrobin
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
