#!/usr/bin/env bash
# Bash script Requirements:
#	Configure HAproxy so that it send traffic to web-01 and web-02
#	Distribute requests using a roundrobin algorithm
#	Make sure that HAproxy can be managed via an init script

sudo apt-get update
sudo apt-get install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo chown -R ubuntu /etc/haproxy
sudo cat <<EOT > /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend my_servers

backend my_servers
    balance roundrobin
    server web-01 54.210.106.234:80
    server web-02 100.26.160.191:80
EOT


sudo systemctl enable haproxy.service
sudo systemctl restart haproxy.service
