#!/usr/bin/env bash
# Bash script Requirements:
#	Configure HAproxy so that it send traffic to web-01 and web-02
#	Distribute requests using a roundrobin algorithm
#	Make sure that HAproxy can be managed via an init script

sudo apt-get update
sudo apt-get install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cat <<EOT > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.210.106.234-web-01:80 check
    server web-02 100.26.160.191-web-02:80 check
EOT


sudo systemctl enable haproxy.service
sudo systemctl restart haproxy.service
