#!/usr/bin/env bash
# Prints Best School for all other iterations bad luck for the fourth iteration and good luck for the eighth

i=1
while (( i<=10 ))
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((i++))
done
